### ISSUE TITLE
can't login (used to work, stopped working 2 days ago)

### ISSUE THREAD

**Issue by AmagamiAimu** [Mikubill/pixivpy-async#15]
_HTTP 400: {'has_error': True, 'errors': {'system': {'message': 'Invalid grant_type parameter or parameter missing', 'code': 1508}}, 'error': 'invalid_grant'}_

**Comment by Mikubill** [comment]
https://github.com/upbit/pixivpy/issues/158. I will add some fix for this issue later.

**Comment by Dynista** [comment]
Hi @Mikubill, was a fix for this issue found?
