### ISSUE TITLE
bapi.py 中download方法如果传入的path没有拓展名会报错

### ISSUE THREAD

**Issue by PainterPuppets** [Mikubill/pixivpy-async#6]
https://github.com/Mikubill/pixivpy-async/blob/master/pixivpy_async/bapi.py#L148

如果没有拓展名，这一行代码会报错

**Comment by Mikubill** [comment]
我太懒了qwq

fixed(https://github.com/Mikubill/pixivpy-async/commit/4e110edd9000ade3584a30b904a1a0fc18d50226)

**Comment by Mikubill** [comment]
closed. (4e110ed)
